platform :ios, '18.0'

# Modüler başlıkları zorla
use_modular_headers!

require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'newApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath]
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
